on:
  push:
    branches:
      - master
      - prod

name: Translate Deployments
jobs:
  push:
    name: Invoke Subscriptions Docker Build Pipeline
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
      with:
        role-to-assume: ${{ secrets.GDBP_AWS_IAM_ROLE_ARN }}
        aws-region: us-west-2

    - name: Translate Deployments
      uses: brave-intl/general-docker-build-pipeline-action@561b579abfb43a2cd0343e68cec85336b90c95d4 # v1.0.40
